package com.github.deliberateq.qsort.gui;

import com.github.deliberateq.util.event.EventType;

public enum Events implements EventType {

	MATRIX, APPLICATION_EXIT, ANALYZED, ROTATIONS, ADD_ROTATION, STATUS, STATUS_FINISHED, OPEN, FILTER, DATA_CHANGED, ADD_VENN, OPEN_OBJECT, VENN, SET_REFERENCE, REFERENCE_SET, SET_REFERENCE_REQUESTED, TABLE_CHANGED, PREFERENCES, OPEN_SAMPLES, NEW_DATA_COMBINATION, UPDATE_LOOK_AND_FEEL;
}
